apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift-transfer
  labels:
    app: swift-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swift-transfer
  template:
    metadata:
      labels:
        app: swift-transfer
    spec:
      containers:
        - name: swift-transfer
          image: swift-transfer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/swiftpay
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
